/* 
 * File:   main.cpp
 * Author: Andrew Kim
 * Created on November 19, 2016, 11:26 AM
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */

//System Libraries
#include <iostream>
#include <cstdlib>
#include <map>
using namespace std;

char findTheDifference(string, string);

int main(int argc, char** argv)
{
    string s = "abceads";
    string t = "abcads";
    
    cout << findTheDifference(s, t);
    
    return 0;
}

char findTheDifference(string s, string t)
{
    //Compare
    int a = s.size();
    int b = t.size();
    char answer = s[0];
    for(int i = 1; i < a; i++)
    {
        answer = answer ^ s[i];
    }
    for(int i = 0; i < b; i++)
    {
        answer = answer ^ t[i];
    }
    return answer;
}

